#!/usr/bin/python

import importlib, scandir, os, sys
scriptroot = os.path.dirname(os.path.realpath(__file__))
sys.path.append(scriptroot + "/mods")
sys.path.append(scriptroot + "/libs")


if __name__ == "__main__":
	modulenames = []
	mf = scandir.walk(scriptroot+"/mods")
	for i in list(mf)[0][2]:
		if i[-3:] == ".py":
			modulenames.append( i[:-3] )
	
	if len(sys.argv) < 2 or sys.argv[1] not in modulenames:
		print sys.argv[0],"<modulename>"
		for mod in modulenames:
			module = importlib.import_module(mod)
			class_ = getattr(module, mod)
			m = class_()
	else:
		mod = sys.argv[1]
		module = importlib.import_module(mod)
		class_ = getattr(module, mod)
		m = class_(sys.argv[2:])
		m.start()








